name: deploy
on:
  push:
  # pull_request:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7
          architecture: x64

      - name: Install dependencies
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pytest-cov
          pip install -r requirements.txt
        # if ( Test-Path -Path .\requirements.txt ) {pip install -r .\requirements.txt}

      - name: Run flake8
        # uses: suo/flake8-github-action@releases/v1
        run: |
          flake8 ./code --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ./code --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: "Running unit test..."
        run: python code/test_*.py
